# Generated by Django 3.2 on 2022-03-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=255, null=True, verbose_name='ID')),
                ('question_name', models.TextField(max_length=400, null=True, verbose_name='Question')),
                ('question_description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('option1', models.CharField(blank=True, max_length=200, null=True)),
                ('option2', models.CharField(blank=True, max_length=200, null=True)),
                ('option3', models.CharField(blank=True, max_length=200, null=True)),
                ('option4', models.CharField(blank=True, max_length=200, null=True)),
                ('option5', models.CharField(blank=True, max_length=200, null=True)),
                ('option6', models.CharField(blank=True, max_length=200, null=True)),
                ('option7', models.CharField(blank=True, max_length=200, null=True)),
                ('option8', models.CharField(blank=True, max_length=200, null=True)),
                ('option9', models.CharField(blank=True, max_length=200, null=True)),
                ('option10', models.CharField(blank=True, max_length=200, null=True)),
                ('option11', models.CharField(blank=True, max_length=200, null=True)),
                ('option12', models.CharField(blank=True, max_length=200, null=True)),
                ('option13', models.CharField(blank=True, max_length=200, null=True)),
                ('option14', models.CharField(blank=True, max_length=200, null=True)),
                ('option15', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='QuesModel',
        ),
    ]
