# Generated by Django 3.2 on 2022-03-02 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220301_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_benefits_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_benefits_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_benefits_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
    ]
