# Generated by Django 3.2 on 2022-02-28 05:23

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('products', '0006_auto_20220228_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='healthgoal',
        ),
        migrations.AddField(
            model_name='product',
            name='healthgoal',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
