# Generated by Django 3.2 on 2022-02-28 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220228_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='healthgoal',
        ),
        migrations.AddField(
            model_name='product',
            name='healthgoal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.healthgoal'),
        ),
    ]
